const ACTIONS = {
  INITAL_LOAD_SUCCESS: "INITAL_LOAD_SUCCESS",
  INITAL_LOAD_FAILURE: "INITAL_LOAD_FAILURE",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  TOGGLE_TODO_SUCCESS: "TOGGLE_TODO_SUCCESS",
  REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE"
};

export default ACTIONS;
