export const REDUCER_ACTIONS = {
  INITAL_LOAD_SUCCESS: "INITAL_LOAD_SUCCESS",
  INITAL_LOAD_FAILURE: "INITAL_LOAD_FAILURE",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  TOGGLE_TODO_SUCCESS: "TOGGLE_TODO_SUCCESS",
  REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
  UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE"
};

export const APP_ACTIONS = {
  INITAL_LOAD_REQUEST: "INITAL_LOAD_REQUEST",
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  TOGGLE_TODO_REQUEST: "TOGGLE_TODO_REQUEST",
  REMOVE_TODO_REQUEST: "REMOVE_TODO_REQUEST"
};
